export enum RabbitMQ {
  UserQueue = 'users',
  ServicesQueue = 'services',
  PostulacionQueue = 'postulaciones',
}


export enum UserMsg {
  CREATE = 'CREATE_USER',
  FIND_ALL = 'FIND_USERS',
  FIND_ONE = 'FIND_USER',
  UPDATE = 'UPDATE_USER',
  DELETE = 'DELETE_USER',
  VALID_USER = 'VALID_USER',
  GENERATE_RECOVERY_CODE = 'GENERATE_RECOVERY_CODE',
  RESET_PASSWORD = 'RESET_PASSWORD',
}

export enum    ServicesMSG{
  CREATE = 'CREATE_SERVICES',
  FIND_ALL =  'FIND_SERVICES',
  FIND_ONE = 'FIND_SERVICE',
  UPDATE = 'UPDATE_SERVICE',
  DELETE = 'DELETE_SERVICE',
  FIND_BY_USER = "FIND_SERVICES_USER",
  GET_AVAILABLE_HOURS = 'GET_AVAILABLE_HOURS',
  FIND_TOP_REQUESTED = 'FIND_TOP_REQUESTED',
  GET_TOTAL_SALES = 'GET_TOTAL_SALES',
  GET_MONTHLY_SALES = 'GET_MONTHLY_SALES',
  GET_ANNUAL_SALES = 'GET_ANNUAL_SALES',
  GET_TOP_SERVICES = 'GET_TOP_SERVICES',
  ADD_REVIEW = 'ADD_REVIEW_SERVICES',
  GET_REVIEWS = 'GET_REVIEWS',
  ADD_CHAT_MESSAGE = 'ADD_CHAT_SERVICE',
  GET_CHATS = " GET_CHATS",
  UPDATE_CHAT = 'UPDATE_CHAT', 
}



export enum PostulacionMsg {
  CREATE = 'CREATE_POSTULACION',
  FIND_ALL = 'FIND_POSTULACIONES',
  FIND_ONE = 'FIND_POSTULACION',
  UPDATE = 'UPDATE_POSTULACION',
  DELETE = 'DELETE_POSTULACION',
  FIND_BY_USER = 'FIND_POSTULACION_USER',
}